In [2]:
import experiment_functions as ef
import numpy as np
beta = 2 #2: 9-14, 3: 22-47, 4: 36-49 
A = ef.SBM(6, 2, 0.4, 0.2)[1]
print(A.toarray())
print()

rand_wts = np.random.rand(6,1)
alpha = rand_wts[:,0].flatten()
C = ef.binary_covariate_weights(2, A, 0, sigma=0.1)
#print(C.toarray())

z = ef.bernoulli(6,0.5)
print(z)
print()

fy_ppom = ef.ppom(beta, C, alpha)
fy_sat = ef.saturation_model(11, beta, C, alpha)
print(fy_ppom(np.ones(6)))
print(fy_sat(np.ones(6)))
print()
print(fy_ppom(z))
print(fy_sat(z))

[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]
 [0 1 1 0 0 1]]

[0 1 0 0 0 1]

[ 8.83960397  8.66491049  8.96752102 20.56879625 20.64286355 17.40379468]
[ 8.83960397  8.66491049  8.96752102 11.         11.         11.        ]

[ 0.41808015  2.141468    1.83180135  8.23906143  0.36294851 13.97655059]
[ 0.41808015  2.141468    1.83180135  8.23906143  0.36294851 11.        ]


In [10]:
import experiment_functions as ef
import numpy as np
beta = 4 #2: 9-14, 3: 22-47, 4: 36-49 
A = ef.SBM(6, 2, 0.4, 0.2)[1]
print(A.toarray())
print()

rand_wts = np.random.rand(6,1)
alpha = rand_wts[:,0].flatten()
C = ef.binary_covariate_weights(2, A, 0, sigma=0.1)
#print(C.toarray())

z = ef.bernoulli(6,0.5)
print(z)
print()

fy_ppom = ef.ppom(beta, C, alpha)
fy_thresh = ef.threshold_model(0.5, beta, C, alpha, A, type="prop")
print(fy_ppom(np.ones(6)))
print(fy_thresh(np.ones(6)))
print()
print(fy_ppom(z))
print(fy_thresh(z))


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 1 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

[0 0 1 0 0 1]

[36.476048   36.55182529 36.99869015 49.7698816  43.2832736  42.91509083]
[36.476048   36.55182529 36.99869015 49.7698816  43.2832736  42.91509083]

[ 0.2696526   0.40524934 36.99869015  1.1661615   0.95573153 42.91509083]
[ 0.          0.         36.99869015  0.          0.         42.91509083]
